#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source $OPENSHIFT_CARTRIDGE_SDK_BASH

pushd ${OPENSHIFT_REPO_DIR} > /dev/null
bundle check
server.rb
popd > /dev/null
