#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

cd $OPENSHIFT_REPO_DIR
nohup bundle exec ./server.rb > $OPENSHIFT_RUBY_LOG_DIR/server.log 2>&1 &